/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { couponItem } from "./types";
export { couponItem } from "./types";
export namespace Components {
    interface CartComponent {
        "headerProps": {
    logo?: 'string'
    storeName?: 'string'
    backComponent?: any,
    page?: string[]
  };
        "submitCallback": Function;
    }
    interface CouponComponent {
        "currency": string;
        "discountAmount": number;
        "handleCouponSubmit": Function;
        "selectedCoupon": Partial<couponItem>;
    }
    interface ShippingComponent {
        "backCallback": Function;
        "headerProps": {
    logo?: 'string'
    storeName?: 'string'
    backComponent?: any,
    page?: string[]
  };
        "submitCallback": Function;
    }
    interface SubmitComponent {
        "returnToStoreHandler": any;
    }
    interface TestingComponent {
    }
}
declare global {
    interface HTMLCartComponentElement extends Components.CartComponent, HTMLStencilElement {
    }
    var HTMLCartComponentElement: {
        prototype: HTMLCartComponentElement;
        new (): HTMLCartComponentElement;
    };
    interface HTMLCouponComponentElement extends Components.CouponComponent, HTMLStencilElement {
    }
    var HTMLCouponComponentElement: {
        prototype: HTMLCouponComponentElement;
        new (): HTMLCouponComponentElement;
    };
    interface HTMLShippingComponentElement extends Components.ShippingComponent, HTMLStencilElement {
    }
    var HTMLShippingComponentElement: {
        prototype: HTMLShippingComponentElement;
        new (): HTMLShippingComponentElement;
    };
    interface HTMLSubmitComponentElement extends Components.SubmitComponent, HTMLStencilElement {
    }
    var HTMLSubmitComponentElement: {
        prototype: HTMLSubmitComponentElement;
        new (): HTMLSubmitComponentElement;
    };
    interface HTMLTestingComponentElement extends Components.TestingComponent, HTMLStencilElement {
    }
    var HTMLTestingComponentElement: {
        prototype: HTMLTestingComponentElement;
        new (): HTMLTestingComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cart-component": HTMLCartComponentElement;
        "coupon-component": HTMLCouponComponentElement;
        "shipping-component": HTMLShippingComponentElement;
        "submit-component": HTMLSubmitComponentElement;
        "testing-component": HTMLTestingComponentElement;
    }
}
declare namespace LocalJSX {
    interface CartComponent {
        "headerProps"?: {
    logo?: 'string'
    storeName?: 'string'
    backComponent?: any,
    page?: string[]
  };
        "submitCallback"?: Function;
    }
    interface CouponComponent {
        "currency"?: string;
        "discountAmount"?: number;
        "handleCouponSubmit"?: Function;
        "selectedCoupon"?: Partial<couponItem>;
    }
    interface ShippingComponent {
        "backCallback"?: Function;
        "headerProps"?: {
    logo?: 'string'
    storeName?: 'string'
    backComponent?: any,
    page?: string[]
  };
        "submitCallback"?: Function;
    }
    interface SubmitComponent {
        "returnToStoreHandler"?: any;
    }
    interface TestingComponent {
    }
    interface IntrinsicElements {
        "cart-component": CartComponent;
        "coupon-component": CouponComponent;
        "shipping-component": ShippingComponent;
        "submit-component": SubmitComponent;
        "testing-component": TestingComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cart-component": LocalJSX.CartComponent & JSXBase.HTMLAttributes<HTMLCartComponentElement>;
            "coupon-component": LocalJSX.CouponComponent & JSXBase.HTMLAttributes<HTMLCouponComponentElement>;
            "shipping-component": LocalJSX.ShippingComponent & JSXBase.HTMLAttributes<HTMLShippingComponentElement>;
            "submit-component": LocalJSX.SubmitComponent & JSXBase.HTMLAttributes<HTMLSubmitComponentElement>;
            "testing-component": LocalJSX.TestingComponent & JSXBase.HTMLAttributes<HTMLTestingComponentElement>;
        }
    }
}
